export function getFormattedPokedexName(pokedexName: string): string {
  const FormattedPokedexNames: { [key: string]: string } = {
    national: 'National',
    kanto: 'Kanto',
    'original-johto': 'Original Johto',
    hoenn: 'Hoenn',
    'original-sinnoh': 'Original Sinnoh',
    'extended-sinnoh': 'Extended Sinnoh',
    'updated-johto': 'Updated Johto',
    'original-unova': 'Original Unova',
    'updated-unova': 'Updated Unova',
    'conquest-gallery': 'Conquest Gallery',
    'kalos-central': 'Kalos Central',
    'kalos-coastal': 'Kalos Coastal',
    'kalos-mountain': 'Kalos Mountain',
    'updated-hoenn': 'Updated Hoenn',
    'original-alola': 'Original Alola',
    'original-melemele': 'Original Melemele',
    'original-akala': 'Original Akala',
    'original-ulaula': "Original Ula'ula",
    'original-poni': 'Original Poni',
    'updated-alola': 'Updated Alola',
    'updated-melemele': 'Updated Melemele',
    'updated-akala': 'Updated Akala',
    'updated-ulaula': "Updated Ula'ula",
    'updated-poni': 'Updated Poni',
    'letsgo-kanto': "Let's Go Kanto",
    galar: 'Galar',
    'isle-of-armor': 'Isle of Armor',
    'crown-tundra': 'Crown Tundra',
    hisui: 'Hisui',
    paldea: 'Paldea',
    kitakami: 'Kitakami',
  };
  return FormattedPokedexNames[pokedexName];
}
